name: crisp
description: A Crisp Chat plugin.
version: 0.0.1
homepage: https://github.com/lunahq/flutter-crisp

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^0.3.20+2
  url_launcher: ^5.4.5
  flutter_webview_plugin: ^0.3.11

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    androidPackage: com.oiluna.crisp
    pluginClass: CrispPlugin
